### ISSUE TITLE
Improve agent image control

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/charts#50]
Our Helm Chart defines a default for the agent.image property, which is the entire URL of the image version compatible with the helm chart's operator version.
Orgs using an internal image repo can't rely on this default, since the URL is different.
We want to let users separately define the image.registry and image.tag values. If they don't define the image.tag, the default value should be taken from the version defined in the operator.

**Comment by meowjesty** [comment]
Is this asking for a change in the mirrord config itself, so that we have:

```json
agent: {
  image: {
    registry: "http://mylocalregistry:7777",
    tag: "custom-image-tag"
  }
}
```

Or just changing the `mirrord-operator.yaml` (and `mirrord-operator/templates/config-map.yaml`?) chart?

```yaml
agent:
  ## example
  ## image: your-internal.registry.io/metalbear-co/agent
  image:
    registry: "mylocalregsitry:7777"
    tag: "custom-image-tag"
```
