### ISSUE TITLE
Ability to reference existing secret with license key in it?

### ISSUE THREAD

**Issue by danielloader** [metalbear-co/charts#6]
Hey is it possible to get a feature request into the helm chart to offer a `secretRef` style way to reference existing secrets that exist in the cluster? 

I would prefer to store the secret externally to the cluster and sync it in via the External Secrets operator. 

Example:

``` yaml

license:
  secretRef:
    name: mirrord-license
```
